dist: xenial
language: ruby
sudo: false
script: 'ci/travis.rb'
before_script:
  - bundle update
cache: bundler
rvm:
  - 2.3.8
gemfile:
  - Gemfile.2.3
env:
  - "GEM=railties"
  - "GEM=ap"
  - "GEM=am,amo,as"
  - "GEM=ar:postgresql"
matrix:
  fast_finish: true
notifications:
  email: false
bundler_args: --without test --jobs 3 --retry 3
services:
  - memcached
  - redis
  - rabbitmq
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_install:
  - sudo apt-get update && sudo apt-get install libfcgi libfcgi-dev
  - gem update --system
  - gem --version
