language: ruby
sudo: false
script: 'ci/travis.rb'
before_script:
  - bundle update
cache: bundler
env:
  matrix:
    - "GEM=railties"
    - "GEM=ap"
    - "GEM=am,amo,as"
    - "GEM=ar:postgresql"
rvm:
  - ree
  - 2.2.2
gemfile:
  - Gemfile
  - gemfiles/Gemfile.ree
matrix:
  fast_finish: true
  exclude:
    - rvm: ree
      gemfile: Gemfile
    - rvm: 2.2.2
      gemfile: gemfiles/Gemfile.ree
notifications:
  email: false
bundler_args: --without test --jobs 3 --retry 3
services:
  - memcached
  - redis
  - rabbitmq
addons:
  postgresql: "9.3"
before_install:
  - gem update --system 1.8.25
  - gem --version
